create table student (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        primary key (id)
    );
insert into student(id, first_name, last_name, email) values(20001,'Adam','Sharma', 'abc@gamil.com');
insert into student(id, first_name, last_name, email) values(20002,'john','Sharma', 'xyz@gamil.com');
insert into student(id, first_name, last_name, email) values(20003,'Jane','Sharma', 'pqr@gamil.com');
insert into student(id, first_name, last_name, email) values(20004,'Peter','Sharma', 'bnm@gamil.com');